### ISSUE TITLE
[Docs] Intermediate Projects

### ISSUE THREAD

**Issue by laisfrigerio** [laisfrigerio/app-ideas#2]
We should copy all the content/files from the [this link](https://github.com/florinpop17/app-ideas/tree/master/Projects/2-Intermediate) into the folder `Projects/2-Intermediate` - [see this PR example](https://github.com/laisfrigerio/app-ideas/pull/1)

- [x] Bit Masks	        
- [x] Book Finder App	    
- [x] Calculator CLI	    
- [x] Card Memory Game	
- [x] Charity Finder App	
- [x] Chrome Theme Extension
- [x] Currency Converter	   
- [x] Drawing App	           
- [x] Emoji Translator App
- [x] Flashcards App	       
- [x] Flip Art App	       
- [x] Game Suggestion App	       
- [x] GitHub Profiles	           
- [x] HighStriker Game	       
- [x] Image Scanner	           
- [x] Markdown Previewer      
- [x] Markdown Table Generator
- [x] Math Editor	               
- [x] Meme Generator App       	
- [x] Name Generation using RNNs	
- [x] Password Generator	        
- [x] Podcast Directory	        
- [x] QR Code Badge Generator	    
- [x] Regular Expression Helper
- [x] Sales Reciepts App	       
- [x] Simple Online Store      
- [x] Sports Bracket Generator
- [x] String Art               
- [x] This or That Game
- [x] Timezone Slackb ot
- [x] To-Do App	       
- [x] Typing             
- [x] Voting App

**Comment by Pritam0077** [comment]
can i work?

**Comment by laisfrigerio** [comment]
Hi, @Pritam0077 

Sure!!! I'll assign you

**Comment by laisfrigerio** [comment]
[The PR related to this issue](https://github.com/laisfrigerio/app-ideas/pull/5)
